add CLI interface

diff --git a/bashbreak b/bashbreak
--- a/bashbreak
+++ b/bashbreak
@@ -1,16 +1,20 @@
 #!/bin/bash
-
-t_work=600 # work sprint time 
-t_short_break=60 # short break in seconds
-t_long_break=900 # long break in seconds
-n_short_break=3 # number of short breaks before long break
-
+version="0.2.0"
+# exit if instance already running
 pcount=`pgrep --count bashbreak`
 if [ $pcount -gt 1 ]
 then
-  echo "Another bashbreak instance already running, kill it before starting a new one (type: pkill -9 bashbreak)."
+  echo "Another bashbreak instance is already running, kill it before starting a new one (type: pkill -9 bashbreak)."
   exit	  
 fi
+
+# default parameters
+n_session=0 # number of work sessions, 0 means infinite
+t_work=600 # work sprint time in seconds 
+t_short_break=60 # short break in seconds
+t_long_break=900 # long break in seconds
+n_short_break=3 # number of short breaks before long break
+quiet=false
 
 # convert time to ms or min
 (( t_work_min=t_work/60 ))
@@ -18,8 +22,10 @@ fi
 (( t_long_break_ms=t_long_break*1000 ))
 (( t_long_break_min=t_long_break/60 ))
 
-# make trap to notify on kill signal
-trap 'notify-send "bashbreak" "Exited."; echo "`date +"%H:%M"` Exiting bashbreak."; exit' SIGINT SIGTERM SIGKILL
+# define functions
+help() {
+		printf '%b\n' "bashbreak v. $version\n\nUse:\n\tbashbreak [OPTION]... \n\nOptions:\n -n\t\tSpecify number of work sessions\n -h\t\tPrint this help\n -q\t\tQuiet mode (no output to stdout)"
+}
 
 short_break() {
   for i in `seq 1 $n_short_break`
@@ -59,13 +65,76 @@ check_idle() {
   echo "`date +"%H:%M"` Starting next work sprint." >&1
 }
 
-# start of program
-msg="Starting session with $t_work_min min work sprints: $n_short_break x $t_short_break s short breaks before a $t_long_break_min min long break."
-echo "`date +"%H:%M"` $msg" >&1
-notify-send "bashbreak" "$msg" -t 10000
-while true 
-do
-  short_break $n_short_break
-  sleep $t_work
-  long_break
+# CLI loop
+while getopts ":n::hq" OPT ; do
+  case $OPT in
+
+    h)
+    ## print help and exit
+    help
+    exit;;
+
+    n)
+    n_session=$OPTARG;;
+
+    q)
+    # suppress output to stdout 
+    quiet=true;;
+
+    \?)
+    ## print if unknown option supplied
+    printf '%b' "Invalid option: -""$OPTARG""\n\n"
+    help
+    exit;;
+    
+    :)
+    ## print if no option arguments supplied
+    printf '%b' "Option -""$OPTARG"" requires an argument.\n"
+    exit;;
+    
+  esac
 done
+
+# main program 
+main() {
+  # make trap to notify on kill signal
+  trap 'notify-send "bashbreak" "Exited."; echo "`date +"%H:%M"` Exiting bashbreak."; exit' SIGINT SIGTERM SIGKILL
+
+  if [ $n_session -eq 0 ]; then 
+    msg="Starting work sessions with $t_work_min min work sprints and $t_short_break s short breaks $n_short_break times before a $t_long_break_min min long break."
+  else
+    msg="Starting $n_session work session(s) with $t_work_min min work sprints and $t_short_break s short breaks $n_short_break times before a $t_long_break_min min long break."
+  fi
+
+  if [ $quiet = false ]; then
+    echo "`date +"%H:%M"` $msg" >&1
+  fi
+
+  notify-send "bashbreak" "$msg" -t 10000
+
+  # main loop 
+  if [ $n_session -eq 0 ]; then 
+    while true; do
+      short_break $n_short_break
+      sleep $t_work
+      long_break
+      i=i+1
+    done
+  else
+    for i in `seq 1 $n_session`; do
+      short_break $n_short_break
+      sleep $t_work
+      long_break
+      i=i+1
+    done
+  fi
+}
+
+main
+# run main if options with correct arguments OR no options were passed
+#if [ $OPTIND -eq 1 ] || [ $OPTIND -eq 3 ]
+#then 
+#  main
+#fi
+
+exit
