change quiet flag to verbose, add echo_v function, bump v to 0.3.0

diff --git a/bashbreak b/bashbreak
--- a/bashbreak
+++ b/bashbreak
@@ -14,7 +14,7 @@ t_work=600 # work sprint time in seconds
 t_short_break=60 # short break in seconds
 t_long_break=900 # long break in seconds
 n_short_break=4 # number of short breaks before long break
-quiet=false
+verbose=false
 
 # convert time to ms or min
 (( t_work_min=t_work/60 ))
@@ -23,15 +23,23 @@ quiet=false
 (( t_long_break_min=t_long_break/60 ))
 
 # define functions
-help() {
+function help() {
   printf '%b\n' "bashbreak v. $version\n\nUse:\n\tbashbreak [OPTION]... \n\nOptions:\n -n\t\tSpecify number of work sessions\n -h\t\tPrint this help\n -q\t\tQuiet mode (no output to stdout)"
 }
 
-short_break() {
+function echo_v() {
+  # prints message if verbose option set
+  local msg="${@}"
+  if [[ "${verbose}" == true ]]; then
+    echo "${msg}"
+  fi
+}
+
+function short_break() {
   for i in `seq 1 $n_short_break`; do
     msg="Take a $t_short_break s break. ($i/$1)"
     sleep $t_work
-    echo "`date +"%H:%M"` $msg" >&1
+    echo_v "`date +"%H:%M"` $msg" >&1
     notify-send "bashbreak" "$msg" --expire-time="$t_short_break_ms" --hint=int:transient:1
     sleep $t_short_break
     # continue only if user is not idle (requires xprintidle)
@@ -39,15 +47,15 @@ short_break() {
   done
 }
 
-long_break() {
+function long_break() {
   msg="Take a $t_long_break_min min break."
-  echo "`date +"%H:%M"` $msg" >&1
+  echo_v "`date +"%H:%M"` $msg" >&1
   notify-send "bashbreak" "$msg" --expire-time="$t_long_break_ms" --hint=int:transient:1
   sleep $t_long_break
   check_idle
 }
 
-check_idle() {
+function check_idle() {
   if ! [ -x '$(command -v xprintidle)' ]; then
     t_idle=`xprintidle` # user idle time in ms
     (( t_idle_=$t_idle+1 ))
@@ -58,37 +66,35 @@ check_idle() {
   else
     echo '`date +"%H:%M"` xprintidle not found. Not checking for user idle.' >&2
   fi
-  echo "`date +"%H:%M"` Starting next work sprint." >&1
+  echo_v "`date +"%H:%M"` Starting next work sprint." >&1
 }
 
 # CLI loop
-while getopts ":n::hq" OPT ; do
+optstring=":hvn:"
+while getopts $optstring OPT; do
   case $OPT in
-
-    h) # print help and exit
-    help; exit;;
-
-    n)
-    n_session=$OPTARG;;
-
-    q) # suppress output to stdout
-    quiet=true;;
-
-    \?) # print if unknown option supplied
-    printf '%b' "Invalid option: -""$OPTARG""\n\n"
-    help; exit;;
-
-    :) # print if no option arguments supplied
-    printf '%b' "Option -""$OPTARG"" requires an argument.\n"
-    exit;;
-
+    h) 
+      help; exit;;
+    n) 
+      n_session=${OPTARG};;
+    v) 
+      verbose=true;; # output status messages to stdout
+    \?)
+      # print if unknown option supplied
+	  echo "Invalid option: -${OPTARG}."
+	  echo "Use -h to see available options."
+      exit;;
+    :)
+      # print if no option arguments supplied
+      printf '%b' "Option -""$OPTARG"" requires an argument.\n"
+      exit;;
   esac
 done
 
 # main program
-main() {
+function main() {
   # make trap to notify on kill signal
-  trap 'notify-send "bashbreak" "Terminating."; echo "`date +"%H:%M"` Terminating."; exit' SIGINT SIGTERM
+  trap 'notify-send "bashbreak" "Terminating."; echo_v "`date +"%H:%M"` Terminating."; exit' SIGINT SIGTERM
 
   if [ $n_session -eq 0 ]; then
     start_msg="Starting work sessions with $t_work_min min work sprints and $t_short_break s short breaks $n_short_break times before a $t_long_break_min min long break."
@@ -99,9 +105,7 @@ main() {
   fi
 
   # send start message
-  if [ $quiet = false ]; then
-    echo "`date +"%H:%M"` $start_msg" >&1
-  fi
+  echo_v "`date +"%H:%M"` $start_msg" >&1
   notify-send "bashbreak" "$start_msg" --expire-time=10000 --hint=int:transient:1
 
   # main loop
