remove periods from messages

diff --git a/bashbreak b/bashbreak
--- a/bashbreak
+++ b/bashbreak
@@ -29,11 +29,11 @@ function help() {
 function print_start_msg() {
   # adapt start msg to number of sessions
   if [ "$n_session" -eq 0 ]; then
-    start_msg="Starting work sessions with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break."
+    start_msg="Starting work sessions with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break"
   elif [ "$n_session" -eq 1 ]; then
-    start_msg="Starting work session with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break."
+    start_msg="Starting work session with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break"
   else
-    start_msg="Starting $n_session work sessions with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break."
+    start_msg="Starting $n_session work sessions with $t_work min work sprints and $t_short_break min short breaks $n_short_break times before a $t_long_break min long break"
   fi
   echo_v "$(date +'%H:%M') $start_msg"
   notify-send "bashbreak" "$start_msg" --expire-time=10000 --hint=int:transient:1
@@ -71,7 +71,7 @@ function run_work_sprint() {
   j=0
   while [ $j -le $t_sleep ]; do 
     sec_remaining=$(( $t_sleep - $j ))
-    log_msg="$(pretty_time $sec_remaining) until $next_event."
+    log_msg="$(pretty_time $sec_remaining) until $next_event"
     write_mem "$log_msg" 
     sleep 1
     let "j+=1"
@@ -85,7 +85,7 @@ function run_break() {
   j=0
   while [ $j -le $t_sleep ]; do 
     sec_remaining=$(( $t_sleep - $j ))
-    log_msg="$(pretty_time $sec_remaining) until $next_event."
+    log_msg="$(pretty_time $sec_remaining) until $next_event"
     write_mem "$log_msg" 
     sleep 1
     let "j+=1"
@@ -133,7 +133,7 @@ function work_session() {
   fi
 
   # start long break
-  msg="Take a $t_long_break min break."
+  msg="Take a $t_long_break min break"
   echo_v "$(date +'%H:%M') $msg"
   notify-send "bashbreak" "$msg" --expire-time="$t_long_break_ms" --hint=int:transient:1
   run_break "$t_long_break_s" 
@@ -146,17 +146,17 @@ function check_idle() {
   if [ "$t_idle" -gt 5000 ]; then
       (( t_idle_=t_idle+1 ))
       while [ "$t_idle_" -ge "$t_idle" ]; do
-        write_mem "User idle."
+        write_mem "User idle"
         sleep 1
         t_idle_=$(xprintidle)
       done
   fi
   else
-    echo "$(date +'%H:%M') xprintidle not found. Not checking for user idle." >&2
+    echo "$(date +'%H:%M') xprintidle not found. Not checking for user idle" >&2
   fi
-  echo_v "$(date +'%H:%M') Starting next work sprint."
+  echo_v "$(date +'%H:%M') Starting next work sprint"
   if [[ $show_work_sprint_start == true ]]; then
-    notify-send "bashbreak" "Starting next work sprint."
+    notify-send "bashbreak" "Starting next work sprint"
   fi
 }
 
@@ -183,8 +183,8 @@ function get_status() {
 
 function kill_running() {
   # clear memory and kill running instance
-  notify-send "bashbreak" "Terminated."
-  echo_v "Terminated."
+  notify-send "bashbreak" "Terminated"
+  echo_v "Terminated"
   clear_mem
   pkill -9 "bashbreak" 
 }
@@ -232,11 +232,11 @@ if [ "$pcount" -gt 1 ]; then
       q)
         kill_running;;
       \?)
-        echo "Another bashbreak instance is already running, quit it before starting a new one (type: bashbreak -q)."
+        echo "Another bashbreak instance is already running, quit it before starting a new one (type: bashbreak -q)"
         exit;;
     esac
   done
-  echo "Another bashbreak instance is already running, quit it before starting a new one (type: bashbreak -q)."
+  echo "Another bashbreak instance is already running, quit it before starting a new one (type: bashbreak -q)"
   exit
 fi
 
@@ -258,12 +258,12 @@ while getopts $optstring OPT; do
       kill_running;;
     \?)
       # print if unknown option supplied
-      echo "Invalid option: -${OPTARG}."
-      echo "Use -h to see available options."
+      echo "Invalid option: -${OPTARG}"
+      echo "Use -h to see available options"
       exit;;
     :)
       # print if no option arguments supplied
-      echo "Option -${OPTARG} requires an argument."
+      echo "Option -${OPTARG} requires an argument"
       exit;;
   esac
 done
@@ -271,7 +271,7 @@ done
 # main program
 function main() {
   # make trap to notify and clear mem on kill signal
-  trap 'notify-send "bashbreak" "Terminated."; echo_v "`date +"%H:%M"` Terminated."; clear_mem; exit' SIGINT SIGTERM
+  trap 'notify-send "bashbreak" "Terminated"; echo_v "`date +"%H:%M"` Terminated"; clear_mem; exit' SIGINT SIGTERM
   convert_time
   print_start_msg
   # main loop
